# Generated by Django 5.0.6 on 2026-08-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(default='General inquiry', max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('spam', 'Spam')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('stem', 'STEM'), ('software', 'Software'), ('financials', 'Financials')], default='software', max_length=20)),
                ('icon', models.CharField(default='fa-solid fa-graduation-cap', help_text='FontAwesome class.', max_length=50)),
                ('level', models.CharField(blank=True, help_text='e.g. Beginner, Intermediate.', max_length=50)),
                ('duration', models.CharField(blank=True, help_text='e.g. 8 weeks.', max_length=80)),
                ('curriculum', models.TextField(blank=True, help_text='One topic per line.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('media_type', models.CharField(choices=[('image', 'Image / Poster'), ('video', 'Video Embed')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube (or other embeddable) URL for video items.')),
                ('link', models.URLField(blank=True, help_text='Optional external link / project page.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Media Item',
                'verbose_name_plural': 'Media Portfolio',
                'ordering': ['sort_order', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fa-solid fa-screwdriver-wrench', max_length=50)),
                ('deliverables', models.TextField(blank=True, help_text='One deliverable per line.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_subtitle', models.TextField(default='We design, build, and deploy offline-first software systems, run a practical skills academy, and deliver ICT consultancy — serving schools, SACCOs, and institutions across Uganda.')),
                ('academy_intro', models.TextField(blank=True, default='Practical, hands-on courses for adult learners and students.')),
                ('services_intro', models.TextField(blank=True)),
                ('gallery_intro', models.TextField(blank=True)),
                ('whatsapp_number', models.CharField(default='256700000000', help_text="International format, no '+', e.g. 256700000000.", max_length=20)),
                ('contact_email', models.EmailField(default='info@jdhub.example', max_length=254)),
                ('address', models.CharField(blank=True, default='Kampala, Uganda', max_length=255)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('tagline', models.CharField(help_text='One-line value proposition.', max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('education', 'Education / School'), ('finance', 'Finance / SACCO'), ('database', 'Database / DBMS'), ('custom', 'Custom Software')], default='custom', max_length=20)),
                ('icon', models.CharField(default='fa-solid fa-microchip', help_text="FontAwesome class, e.g. 'fa-solid fa-school'.", max_length=50)),
                ('features', models.TextField(blank=True, help_text='One feature per line. Rendered as a checklist.')),
                ('tech_stack', models.CharField(blank=True, help_text="Comma-separated, e.g. 'Django, PWA, SQLite, Bootstrap'.", max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Flagship System',
                'verbose_name_plural': 'Flagship Systems',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
