# Generated by Django 5.0.6 on 2026-08-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('stem', 'STEM'), ('software', 'Software'), ('financials', 'Financials'), ('ai', 'AI')], default='software', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='academy_intro',
            field=models.TextField(blank=True, default='Paid, instructor-led online classes on Google Meet. Enrol and pay, then join live sessions for students (Nursery–S6) and adult learners.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='jordandesignhub@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(default='We build web & mobile apps (Android and iOS), run a paid online academy on Google Meet, deliver church media training, connect holiday tutors to students (Nursery–S6), design graphics, and teach AI optimization — across Uganda and beyond.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(default='256754687597', help_text="International format, no '+', e.g. 256754687597.", max_length=20),
        ),
    ]
