# Generated by Django 5.0.6 on 2026-08-18 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_alter_course_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('subject', models.CharField(blank=True, help_text='Specific subject or topic (e.g. Mathematics, English, Prompt Engineering).', max_length=200)),
                ('level', models.CharField(choices=[('nursery', 'Nursery'), ('p1_p3', 'P1 – P3'), ('p4_p6', 'P4 – P6'), ('p7', 'P7'), ('s1_s2', 'S1 – S2'), ('s3_s4', 'S3 – S4 (O-Level)'), ('s5_s6', 'S5 – S6 (A-Level)'), ('adult', 'Adult Learner')], default='adult', max_length=20)),
                ('schedule', models.CharField(blank=True, help_text="Preferred day/time or 'flexible'.", max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Anything the student wants us to know.')),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('meet_link', models.URLField(blank=True, help_text='Google Meet link — set automatically when approved (once Google Meet is wired up).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='Optional — pick a course if relevant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolments', to='hub.course')),
            ],
            options={
                'verbose_name': 'Enrolment',
                'verbose_name_plural': 'Enrolments',
                'ordering': ['-created_at'],
            },
        ),
    ]
