# Generated by Django 5.0.6 on 2026-08-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_enrolment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='airtel_name',
            field=models.CharField(blank=True, default='Jordan Design Hub', help_text='Name registered on the Airtel Money account.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='airtel_number',
            field=models.CharField(blank=True, default='256754687597', help_text="Airtel Money number (international format, no '+').", max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='momo_name',
            field=models.CharField(blank=True, default='Jordan Design Hub', help_text='Name registered on the MTN Mobile Money account.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='momo_number',
            field=models.CharField(blank=True, default='256754687597', help_text="MTN MoMo number (international format, no '+').", max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_instructions',
            field=models.TextField(blank=True, default='1. Choose MTN MoMo or Airtel Money.\n2. Send fees to the number shown.\n3. Keep the transaction ID.\n4. Confirm on WhatsApp with your transaction ID.\n', help_text='Step-by-step payment instructions shown after enrolment.'),
        ),
    ]
