# Generated by Django 5.0.6 on 2026-08-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_sitesettings_airtel_name_sitesettings_airtel_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='screenshots',
            field=models.TextField(blank=True, help_text="One screenshot per line as 'path|caption'. Paths are relative to MEDIA_ROOT."),
        ),
    ]
